version: '3.8'
services:
  jira:
    image: atlassian/jira-software:10.0.0
    container_name: jira-software
    hostname: jira-software
    domainname: rpi5.local
    restart: always
    ports:
      - "${JIRA_PORT}:8080"
    volumes:
      - jiraVolume:/var/atlassian/application-data/jira
    environment:
      ATL_JDBC_URL: "jdbc:postgresql://db:5432/jiradb"
      ATL_DB_DRIVER: "org.postgresql.Driver"
      ATL_JDBC_USER: "${JIRA_USER}"
      ATL_JDBC_PASSWORD: "${JIRA_JDBC_PASSWORD}"
      ATL_DB_TYPE: "postgres72"
    networks:
      - jira
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: jira-db
    hostname: jira-db
    restart: always
    ports:
      - "${JIRA_DB_PORT}:5432"
    volumes:
      - jiraDbVolume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${JIRA_USER}"
      POSTGRES_PASSWORD: "${JIRA_JDBC_PASSWORD}"
      POSTGRES_DB: jiradb
    networks:
      - jira

volumes:
  jiraVolume:
  jiraDbVolume:

networks:
  jira:
    external: true
