version: '3.8'
services:
  nexus:
    image: sonatype/nexus3:3.79.1
    container_name: nexus
    hostname: nexus
    restart: always
    ports:
      - "${NEXUS_PORT}:8081"
      - "${NEXUS_DOCKER_PORT}:8082"
      - "${NEXUS_DOCKER_PORT_2}:8083"
    volumes:
      - nexus_data:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=/nexus-data/javaprefs
      - NEXUS_CONTEXT=
      - DB_HOST=nexus-db
      - DB_PORT=5432
      - DB_NAME=${NEXUS_DB_NAME}
      - DB_USER=${NEXUS_DB_USER}
      - DB_PASSWORD=${NEXUS_DB_PASSWORD}
    networks:
      - nexus
      - nexus-db
    depends_on:
      - nexus-db

  nexus-db:
    image: postgres:14
    container_name: nexus-db
    hostname: nexus-db
    restart: always
    ports:
      - "${NEXUS_DB_PORT}:5432"
    volumes:
      - nexus_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${NEXUS_DB_USER}
      POSTGRES_PASSWORD: ${NEXUS_DB_PASSWORD}
      POSTGRES_DB: ${NEXUS_DB_NAME}
    networks:
      - nexus-db

volumes:
  nexus_data:
  nexus_db_data:

networks:
  nexus:
    external: true
  nexus-db:
    external: true