version: '3.8'

services:
  mailserver:
    image: mailserver/docker-mailserver:15.0.2
    container_name: mailserver
    hostname: mailserver
    restart: always
    domainname: rpi5.local
    networks:
      - jira
      - mail
    ports:
      - "${SMTP_PORT}:25"             # SMTP
      - "${SMTP_SUBMISSION_PORT}:587" # SMTP (Submission)
      - "${IMAP_PORT}:993"            # IMAP
    volumes:
      - /srv/mailserver/maildata:/var/mail
      - /srv/mailserver/mailstate:/var/mail-state
      - /srv/mailserver/config:/tmp/docker-mailserver
    environment:
      - ONE_DIR=1
      - DMS_DEBUG=0
    cap_add:
      - NET_ADMIN

  roundcube:
    image: roundcube/roundcubemail:1.6.10-apache
    container_name: roundcube
    hostname: roundcube
    restart: always
    networks:
      - mail
    ports:
      - "${ROUNDCUBE_PORT}:80"
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=mailserver
      - ROUNDCUBEMAIL_SMTP_SERVER=mailserver
      - ROUNDCUBEMAIL_SMTP_PORT=587
      - ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE=5M
      - ROUNDCUBEMAIL_MEMORY_LIMIT=64M
    volumes:
      - /srv/roundcube/config:/var/roundcube/config
      - /srv/roundcube/logs:/var/roundcube/logs
      - /srv/roundcube/data:/var/roundcube/data

networks:
  jira:
    external: true
  mail:
    external: true
